[project]
name = "rag-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.6.0",
    "python-dotenv>=1.0.0",
    "streamlit>=1.50.0",
]
